### ISSUE TITLE
Website publish checklist

### ISSUE THREAD

**Issue by Beramos** [Beramos/dingDongsGent#3]
- [x] Switch WP debugger off
- [x] address on successful redirect
- [x] Touch support mobile devices
- [x] section 3, published by ...
- [x] NarvBars drukken
- [x] pijlke drukken
- [x] pagina 4: nog een waarschuwing dat het paypal adres het adres dat gebruikt wordt om te versturen
- [x] redirect from paypal after clicking return to dingdongsGent should go back to homepage, not to basket
- [x] down arrow second position
- [x] on live website change url of all figures to the absolute path so that all subpages can find the figures
- [x] Fix bug: where scrolling down from last section after refreshing is possible

**Comment by fwyffels** [comment]
- [x] page 1: png to jpg
- [x] page 1: add side text 
- [x] page 3: text + logo baryon
- [x] page 4: bottom bar edit mail, add Facebook + twitter hashtag + webmaster head
